name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  release:
    strategy:
      matrix:
        include:
          - os: macos-latest
            platform: mac

          - os: windows-latest
            platform: win

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - run: npm ci

      # 如果以后用了 keytar 等原生模块
      - run: npx electron-rebuild -f
        if: runner.os != 'Windows'

      - run: npx electron-rebuild.cmd -f
        if: runner.os == 'Windows'

      - run: npm run dist

      - name: Attest
        uses: actions/attest-build-provenance@v3
        with:
          subject-path: dist/**

      - name: Upload
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/*.zip
            dist/*.exe
            dist/*.dmg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
